import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

/* ── Brand palette ─────────────────────────────────────────────────────────── */
const C = {
  red:      [220, 68,  72],
  green:    [38,  185, 103],
  dark:     [16,  16,  22],
  navy:     [30,  32,  50],
  slate:    [70,  75,  100],
  mid:      [120, 125, 150],
  light:    [200, 202, 215],
  white:    [255, 255, 255],
  offWhite: [248, 248, 252],
  gold:     [200, 140, 20],
};

/* ── Utility: strip emojis + swap ₹ for "Rs." (jsPDF Helvetica = ASCII only) ─ */
const stripPDF = (str = '') =>
  String(str)
    .replace(/₹/g, 'Rs. ')
    .replace(/[\u{1F000}-\u{1FFFF}]/gu, '')          // Supplementary multilingual
    .replace(/[\u2600-\u27BF]/g, '')                  // Misc symbols & dingbats
    .replace(/[\uE000-\uF8FF]/g, '')                  // Private Use Area
    .replace(/[\u{1F300}-\u{1F9FF}]/gu, '')           // Emoji block
    .replace(/·/g, '-')                               // Middle dot -> hyphen
    .replace(/—/g, '-')                               // Em dash -> hyphen
    .replace(/→/g, '->')                              // Arrow -> ASCII
    .replace(/[^\x00-\xFF]/g, '')                     // Strip anything non-Latin-1
    .replace(/\s{2,}/g, ' ')
    .trim();

/* ── Page dimensions ─────────────────────────────────────────────────────── */
const PAGE_W    = 210;
const PAGE_H    = 297;
const MARGIN    = 18;
const CONTENT_W = PAGE_W - MARGIN * 2;

/* ── Helpers ─────────────────────────────────────────────────────────────── */
const setFill = (doc, c)                      => doc.setFillColor(...c);
const setDraw = (doc, c)                      => doc.setDrawColor(...c);
const setFont = (doc, c, sz, style = 'normal') => {
  doc.setFont('helvetica', style);
  doc.setFontSize(sz);
  doc.setTextColor(...c);
};

/* ── Running header + footer on every inner page ─────────────────────────── */
function addPageChrome(doc, tripMeta) {
  // Top bar
  setFill(doc, C.navy);
  doc.rect(0, 0, PAGE_W, 12, 'F');
  setFont(doc, C.white, 8, 'bold');
  doc.text('Vijayawada Travel Planner', MARGIN, 8);
  setFont(doc, C.light, 7);
  doc.text(
    stripPDF(`${tripMeta.people} people - Rs. ${tripMeta.budget.toLocaleString()}/person - ${tripMeta.days} days`),
    PAGE_W - MARGIN, 8, { align: 'right' }
  );

  // Bottom bar
  setFill(doc, C.offWhite);
  doc.rect(0, PAGE_H - 10, PAGE_W, 10, 'F');
  setDraw(doc, C.light);
  doc.setLineWidth(0.2);
  doc.line(MARGIN, PAGE_H - 10, PAGE_W - MARGIN, PAGE_H - 10);
  setFont(doc, C.mid, 7);
  doc.text('Generated by Vijayawada Travel Planner - V3 Heuristic Engine', MARGIN, PAGE_H - 4);
  doc.text(`Page ${doc.internal.getCurrentPageInfo().pageNumber}`, PAGE_W - MARGIN, PAGE_H - 4, { align: 'right' });
}

/* ── Cover page ──────────────────────────────────────────────────────────── */
function drawCoverPage(doc, result, constraints) {
  const meta = result.raw_data.metadata;

  setFill(doc, C.dark);
  doc.rect(0, 0, PAGE_W, PAGE_H, 'F');

  // Red accent stripe
  setFill(doc, C.red);
  doc.rect(0, 0, PAGE_W, 4, 'F');

  // Decorative circle
  setFill(doc, C.navy);
  doc.ellipse(PAGE_W - 30, 60, 80, 80, 'F');

  // Title
  setFont(doc, C.white, 32, 'bold');
  doc.text('Vijayawada', MARGIN, 70);
  setFont(doc, C.red, 32, 'bold');
  doc.text('Travel Planner', MARGIN, 85);

  // Divider
  setFill(doc, C.red);
  doc.rect(MARGIN, 92, 40, 1.5, 'F');

  // Subtitle
  setFont(doc, C.light, 11);
  doc.text('Exclusively built for Vijayawada, Andhra Pradesh', MARGIN, 102);
  setFont(doc, C.mid, 9);
  doc.text('V3 - Heuristic Spatio-Temporal Clustering - O(n^2)', MARGIN, 110);

  // Trip summary card
  const cardY = 130;
  setFill(doc, C.navy);
  doc.roundedRect(MARGIN, cardY, CONTENT_W, 86, 4, 4, 'F');
  setDraw(doc, [40, 45, 70]);
  doc.setLineWidth(0.3);
  doc.roundedRect(MARGIN, cardY, CONTENT_W, 86, 4, 4, 'S');

  setFont(doc, C.light, 8, 'bold');
  doc.text('TRIP SUMMARY', MARGIN + 8, cardY + 10);
  setFill(doc, C.red);
  doc.rect(MARGIN + 8, cardY + 12, 20, 0.5, 'F');

  const totalBudget = (constraints.budget || 0) * (constraints.people_count || 1);
  const rows = [
    ['People',     `${constraints.people_count} travellers`],
    ['Budget',     `Rs. ${(constraints.budget || 0).toLocaleString()} per person  (Rs. ${totalBudget.toLocaleString()} total)`],
    ['Days',       `${meta.actual_days_planned} optimal days${meta.requested_days && meta.requested_days > meta.optimal_days ? ` (requested ${meta.requested_days} - trimmed)` : ''}`],
    ['Interests',  constraints.interests?.length > 0 ? constraints.interests.map(i => i.charAt(0).toUpperCase() + i.slice(1)).join(', ') : 'All categories'],
    ['Algorithm',  'Haversine Greedy + Second-Pass - Peak/Off-Peak traffic modelling'],
    ['AI Layer',   'Gemini 2.5 Flash - formatting & explainability only'],
  ];

  let ry = cardY + 22;
  rows.forEach(([label, value]) => {
    setFont(doc, C.mid, 8);
    doc.text(label, MARGIN + 8, ry);
    setFont(doc, C.white, 8);
    doc.text(stripPDF(value), MARGIN + 52, ry);
    ry += 10;
  });

  // Tagline
  setFont(doc, C.mid, 8);
  doc.text('Data-driven - Zero hallucinations - Deterministic routing', PAGE_W / 2, PAGE_H - 30, { align: 'center' });
  setFont(doc, C.red, 7);
  doc.text('Generated ' + new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' }), PAGE_W / 2, PAGE_H - 22, { align: 'center' });

  // Green bottom accent
  setFill(doc, C.green);
  doc.rect(0, PAGE_H - 4, PAGE_W, 4, 'F');
}

/* ── Section heading ─────────────────────────────────────────────────────── */
function sectionHeading(doc, text, y, color = C.red) {
  setFill(doc, color);
  doc.rect(MARGIN, y, 3, 6, 'F');
  setFont(doc, C.dark, 12, 'bold');
  doc.text(stripPDF(text), MARGIN + 6, y + 5);
  return y + 10;
}

/* ── Day colour by index ─────────────────────────────────────────────────── */
const DAY_COLORS = [C.red, C.green, [200, 120, 20], [30, 144, 255], [140, 120, 220]];

/* ── Single day pages ────────────────────────────────────────────────────── */
function drawDay(doc, day, tripMeta) {
  doc.addPage();
  addPageChrome(doc, tripMeta);

  let y      = 20;
  const color = DAY_COLORS[(day.day - 1) % DAY_COLORS.length];

  // Day banner
  setFill(doc, color);
  doc.rect(0, y, PAGE_W, 18, 'F');
  setFont(doc, C.white, 14, 'bold');
  doc.text(`Day ${day.day}`, MARGIN, y + 12);
  setFont(doc, C.white, 9);
  doc.text(`${day.total_hours}h planned  -  ${day.places.length} places`, PAGE_W - MARGIN, y + 12, { align: 'right' });
  y += 26;

  // ── Places table ──
  y = sectionHeading(doc, 'Places & Visit Times', y, color);
  autoTable(doc, {
    startY: y,
    margin: { left: MARGIN, right: MARGIN },
    head: [['#', 'Place', 'Type', 'Arrive', 'Leave', 'Duration']],
    body: day.places.map((p, i) => [
      i + 1,
      stripPDF(p.name),
      stripPDF((p.type || '').charAt(0).toUpperCase() + (p.type || '').slice(1)),
      p.visit_start || '-',
      p.visit_end   || '-',
      p.avg_time_hours ? `${p.avg_time_hours}h` : '-',
    ]),
    headStyles:          { fillColor: color, textColor: 255, fontStyle: 'bold', fontSize: 8 },
    bodyStyles:          { fontSize: 8, textColor: C.slate },
    alternateRowStyles:  { fillColor: C.offWhite },
    tableLineColor:      C.light,
    tableLineWidth:      0.1,
    columnStyles: {
      0: { cellWidth: 8,  halign: 'center' },
      1: { cellWidth: 65, fontStyle: 'bold', textColor: C.dark },
      2: { cellWidth: 24 },
      3: { cellWidth: 20, halign: 'center' },
      4: { cellWidth: 20, halign: 'center' },
      5: { cellWidth: 20, halign: 'center' },
    },
  });
  y = doc.lastAutoTable.finalY + 10;

  // ── Transport table ──
  if (day.routes?.length > 0) {
    if (y > PAGE_H - 80) { doc.addPage(); addPageChrome(doc, tripMeta); y = 20; }
    y = sectionHeading(doc, 'Traffic-Aware Transport', y, color);

    autoTable(doc, {
      startY: y,
      margin: { left: MARGIN, right: MARGIN },
      head: [['From -> To', 'Dist', 'Drive', 'Auto', 'Uber/Cab', 'Rapido']],
      body: day.routes.map(r => [
        stripPDF(`${r.from} -> ${r.to}`),
        `${r.distance_km} km`,
        `~${r.costs?.mins} min`,
        `Rs. ${r.costs?.auto}`,
        `Rs. ${r.costs?.cab}`,
        `Rs. ${r.costs?.bike}`,
      ]),
      headStyles:          { fillColor: C.navy, textColor: 255, fontSize: 8 },
      bodyStyles:          { fontSize: 8, textColor: C.slate },
      alternateRowStyles:  { fillColor: C.offWhite },
      columnStyles: {
        0: { cellWidth: 72, fontStyle: 'bold', textColor: C.dark },
        1: { cellWidth: 18, halign: 'center' },
        2: { cellWidth: 20, halign: 'center' },
        3: { cellWidth: 22, halign: 'center', textColor: C.green },
        4: { cellWidth: 22, halign: 'center' },
        5: { cellWidth: 22, halign: 'center' },
      },
    });
    y = doc.lastAutoTable.finalY + 10;
  }

  // ── Hotels + Food side by side ──
  const recs = day.recommendations;
  if (recs && (recs.hotels?.length || recs.food?.length)) {
    if (y > PAGE_H - 70) { doc.addPage(); addPageChrome(doc, tripMeta); y = 20; }
    y = sectionHeading(doc, 'Nearby Hotels & Food', y, color);

    const half     = (CONTENT_W - 6) / 2;
    const startY   = y;

    autoTable(doc, {
      startY,
      margin: { left: MARGIN, right: MARGIN + half + 6 },
      head: [['Hotel', 'Price / Night']],
      body: (recs.hotels || []).map(h => [stripPDF(h.name), stripPDF(h.price_range)]),
      headStyles:         { fillColor: C.navy, textColor: 255, fontSize: 7.5 },
      bodyStyles:         { fontSize: 8 },
      alternateRowStyles: { fillColor: C.offWhite },
      columnStyles: {
        0: { fontStyle: 'bold', textColor: C.dark },
        1: { textColor: C.green, halign: 'right' },
      },
    });

    autoTable(doc, {
      startY,
      margin: { left: MARGIN + half + 6, right: MARGIN },
      head: [['Restaurant', 'Cuisine']],
      body: (recs.food || []).map(f => [stripPDF(f.name), stripPDF(f.type)]),
      headStyles:         { fillColor: C.red, textColor: 255, fontSize: 7.5 },
      bodyStyles:         { fontSize: 8 },
      alternateRowStyles: { fillColor: [255, 245, 245] },
      columnStyles: {
        0: { fontStyle: 'bold', textColor: C.dark },
        1: { textColor: C.mid },
      },
    });
  }
}

/* ── Main export ─────────────────────────────────────────────────────────── */
export function downloadPDF(result, constraints) {
  const doc  = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const meta = result.raw_data.metadata;

  const tripMeta = {
    people: constraints.people_count || 1,
    budget: constraints.budget       || 0,
    days:   meta.actual_days_planned,
  };

  // Page 1: Cover (dark themed — no chrome)
  drawCoverPage(doc, result, constraints);

  // Page 2: AI Explanation
  if (result.markdown) {
    doc.addPage();
    addPageChrome(doc, tripMeta);
    let y = 20;
    y = sectionHeading(doc, 'Why This Plan? - AI Explanation', y, C.green);

    const plain = result.markdown
      .replace(/#{1,6}\s+/g, '')
      .replace(/\*\*/g, '')
      .replace(/\*/g, '')
      .replace(/`/g, '')
      .replace(/---/g, '')
      .replace(/₹/g, 'Rs. ')
      // Strip emojis / non-latin characters
      .replace(/[\u{1F000}-\u{1FFFF}]/gu, '')
      .replace(/[\u2600-\u27BF]/g, '')
      .replace(/[^\x00-\xFF]/g, '')
      .replace(/·/g, '-')
      .replace(/—/g, '-')
      .replace(/→/g, '->')
      .replace(/\s{2,}/g, ' ')
      .trim();

    const lines = doc.splitTextToSize(plain, CONTENT_W);
    setFont(doc, C.slate, 8.5);
    lines.forEach(line => {
      if (y > PAGE_H - 18) { doc.addPage(); addPageChrome(doc, tripMeta); y = 20; }
      doc.text(line, MARGIN, y);
      y += 5;
    });
  }

  // Pages per day
  result.raw_data.itinerary.forEach(day => drawDay(doc, day, tripMeta));

  // Save
  const filename = `Vijayawada_Trip_${meta.actual_days_planned}Days_${Date.now()}.pdf`;
  doc.save(filename);
}
